///////////////////////////////////////////////////////////////////////////////
// default includes

#include <winnt.h>
#include <objbase.h>	// needs winnt.h
#include <winbase.h>
#include <wtypes.h>
#include <winuser.h>
#include <winbase.h>
#include <xiosbase>
#include <atldef.h>
#include <atlbase.h>
#include <winuser.h>
#include <comdef.h>
#include <use_ansi.h>
#include <yvals.h>
#include <stddef.h>
#include <cstddef>
#include <xstddef>
#include <eh.h>
#include <exception>
#include <new>
#include <dlgs.h>
#include <winver.h>
#include <winresrc.h>
#include <excpt.h>
#include <stdarg.h>
#include <ctype.h>
#include <afx.h>
#include <afxdlgs.h>
#include <afxole.h>
#include <afxwin.h>
#include <winres.h>
#include <afxres.h>
#include <pshpack4.h>
#include <poppack.h>
#include <pshpack2.h>
#include <string.h>
#include <windef.h>
#include <winerror.h>
#include <pshpack1.h>
#include <wingdi.h>
#include <winnls.h>
#include <wincon.h>
#include <winreg.h>
#include <winnetwk.h>
#include <cderr.h>
#include <dde.h>
#include <ddeml.h>
#include <lzexpand.h>
#include <mmsystem.h>
#include <nb30.h>
#include <rpcdcep.h>
#include <rpcdce.h>
#include <rpcnsi.h>
#include <rpcnterr.h>
#include <rpc.h>
#include <windows.h>
#include <shellapi.h>
#include <winperf.h>
#include <winsock2.h>
#include <mswsock.h>
#include <winsock.h>
#include <wincrypt.h>
#include <commdlg.h>
#include <winspool.h>
#include <prsht.h>
#include <ole.h>
#include <ole2.h>
#include <pshpack8.h>
#include <rpcndr.h>
#include <rpcnsip.h>
#include <stdlib.h>
#include <wtypes.h>
#include <unknwn.h>
#include <objidl.h>
#include <cguid.h>
#include <oleauto.h>
#include <oaidl.h>
#include <oleidl.h>
#include <winsvc.h>
#include <mcx.h>
#include <imm.h>
#include <zmouse.h>
#include <commctrl.h>
#include <wchar.h>
#include <mbstring.h>
#include <tchar.h>
#include <mbctype.h>
#include <afxv_w32.h>
#include <afxv_cpu.h>
#include <afxv_mac.h>
#include <afxv_cfg.h>
#include <afxv_dll.h>
#include <afxver_.h>
#include <stdio.h>
#include <time.h>
#include <limits.h>
#include <crtdbg.h>
#include <setjmp.h>
#include <afxtls_.h>
#include <afxstat_.h>
#include <afxcoll.inl>
#include <afxcoll.h>
#include <afx.inl>
#include <afxmsg_.h>
#include <afxdd_.h>
#include <afxdll_.h>
#include <afxwin1.inl>
#include <afxwin2.inl>
#include <richedit.h>
#include <afxdlgs.inl>
#include <afxext.inl>
#include <ocidl.h>
#include <olectl.h>
#include <afxole.inl>
#include <afxdisp.h>
#include <servprov.h>
#include <docobj.h>
#include <urlmon.h>
#include <afxcom_.h>
#include <richole.h>
#include <afxcmn.inl>
#include <afxplex_.h>
#include <oledlg.h>
#include <afxadv.h>
#include <atlconv.h>
#include <malloc.h>
#include <afxconv.h>
#include <afxpriv2.h>
#include <afxpriv.h>
#include <afxext.h>
#include <atliface.h>
#include <atlconv.cpp>
#include <atlcom.h>
#include <shlguid.h>
#include <afxdb_.h>
#include <sqltypes.h>
#include <sql.h>
#include <sqlucode.h>
#include <sqlext.h>
#include <afxdb.inl>
#include <dbdaoint.h>
#include <daogetrw.h>
#include <dbdaoid.h>
#include <dbdaoerr.h>
#include <afxdao.inl>
#include <afxmt.inl>
#include <useoldio.h>
#include <streamb.h>
#include <ios.h>
#include <istream.h>
#include <ostream.h>
#include <sys\types.h>
#include <cstdlib>
#include <cstdio>
#include <cwchar>
#include <iosfwd>
#include <cstring>
#include <utility>
#include <xmemory>
#include <wctype.h>
#include <cerrno>
#include <errno.h>
#include <climits>
#include <xutility>
#include <xstring>
#include <stdexcept>
#include <typeinfo>
#include <xlocinfo.h>
#include <locale.h>
#include <xlocinfo>
#include <xlocale>
#include <xlocnum>
#include <streambuf>
#include <ios>
#include <ostream>
#include <istream>
#include <afxrich.inl>
#include <afxodlgs.h>
#include <afxdb.h>
#include <afxdao.h>
#include <afxcmn.h>
#include <afxmt.h>
#include <io.h>
#include <iostream.h>
#include <fstream.h>
#include <sys\stat.h>
#include <direct.h>
#include <process.h>
#include <strstrea.h>
#include <cctype>
#include <memory>
#include <iterator>
#include <cwctype>
#include <iostream>
#include <fcntl.h>
#include <share.h>
#include <dos.h>
#include <sys\locking.h>
#include <iomanip.h>
#include <initguid.h>
#include <string>
#include <map>
#include <hash_map>
#include <vector>
#include <list>
#include <deque>
#include <atlstr.h> // ns.net
#define EH_CSTD
