<SCRIPT RUNAT=SERVER LANGUAGE="JavaScript">
// ************************************************************************ 
// Microsoft Scripting Libary 
// Visual InterDev 6.0 EventManager Object for ASP
//
// Copyright 1998 Microsoft Corporation. All Rights Reserved.
// ************************************************************************ 

// IMPLEMENTATION MERGED INTO PM.ASP
// THIS FILE IS NO LONGER INCLUDED BY DTCs.
</SCRIPT>