// ATL Julian date build numbers (YDDD) 
#pragma once 
#define _LIBS_BUILD 3077
#define _LIBS_USER_BUILD "3077"

#define _LIBS_PRODUCT_VERSION_MAJOR 7 
#define _LIBS_USER_PRODUCT_VERSION_MAJOR "7" 
#define _LIBS_PRODUCT_VERSION_MINOR 10 
#define _LIBS_USER_PRODUCT_VERSION_MINOR "10" 

#define _LIBS_FILE_VERSION_MAJOR 7 
#define _LIBS_USER_FILE_VERSION_MAJOR "7" 
#define _LIBS_FILE_VERSION_MINOR 10 
#define _LIBS_USER_FILE_VERSION_MINOR "10" 
#define _LIBS_USER_FULL_VER "7.10.3077"

#ifndef _LIBS_RBLD 
#define _LIBS_RBLD 0 
#define _LIBS_USER_RBLD "0" 
#endif
