a::Pr:
Private
a::Pu:
Public
a::E:
Else
a::D:
Dim
a::If:
If $end$ Then
End If
a::Function:
Function $end$ ( )
End Function
a::Sub:
Sub $end$ ( )
End Sub
a::Do:
Do While $end$
Loop
a::For:
For $end$ To 
Next
a:File header::
'*************************************************************************
'	created:	$DATE$
'	created:	$DAY$:$MONTH$:$YEAR$   $HOUR$:$MINUTE$
'	filename: 	$FILE$
'	file path:	$FILE_PATH$
'	file base:	$FILE_BASE$
'	file ext:	$FILE_EXT$
'	author:		$1$
'	
'	purpose:	$end$
'*************************************************************************

